### ISSUE TITLE
Tanstack Example - Build Output fails

### ISSUE THREAD

**Issue by iDarkLightning** [vonojs/vono#5]
The build output for the included tanstack router example is unable to load the client entry.

![image](https://github.com/vonojs/vono/assets/69070214/c1a9804a-971f-498e-99df-83366b4cb2e1)

To reproduce, inside the tanstack router example located in `examples/tanstack`

```
yarn build
node dist/entry.js
```

My guess is it has something to do with the `Content-Type` headers set for the `/*` match in `server/index.ts`

**Comment by b3nten** [comment]
Hi! I updated the preview commands in the examples as they were still using vite's preview server, which won't work with the build output.
